# Generated by Django 3.2.16 on 2022-11-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('IOS', 'IOS'), ('ANDROID', 'Android')], max_length=30),
        ),
    ]
